# available palettes
#  "latte", "frappe", "macchiato", "mocha" :
palette: "mocha"

subTitle: |
  personal site of e.j. sahala (they/them). (infrequent) musings on technology, coffee, and other stuff

author: "e.j. sahala (they/them)"
description: |
  personal site of e.j. sahala (they/them). (infrequent) musings on coffee, networking, automation, technology, philosophy, and sometimes other stuff.

  #BlackLivesMatter #TransLivesMatter

logoPicture: "images/ejs-sh.svg"
profilePicture: "images/profile.png"
profilePictureAlt: "a photo of e.j. taking a photo"
copyrightFrom: "2022"

# github integration
gh_user_api: "https://api.github.com/users"
gh_user: "ejsdotsh"

# charts
# mermaid: true

# LaTeX
# katex: true

# theme control
#  displayMode: "dark"
#  disableThemeSwitcher: true
#  doNotLoadAnimations: true
#  contentRatio: 0.7

# params.math:
# enable: true
# use: "katex"

## social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
social:
  - name: "linkedin"
    icon: "fab fa-linkedin"
    url: "https://www.linkedin.com/in/ejsdotsh/"
    weight: 10
  - name: "github"
    icon: "fab fa-github"
    url: "https://github.com/ejsdotsh/"
    weight: 20
  - name: "e-mail"
    icon: "fas fa-envelope"
    url: "mailto:contactme@ejs.sh"
    weight: 30
